export { Home } from '../Views/Home'
export { Navbar } from '../Components/Navbar'
export { Footer } from '../Components/Footer'
export { SingIn } from '../Views/SingIn'
export { LoginRoutes } from '../Views/LoginRoutes'
